#import "../../lib/colours.typ": colourPalette

#let chapter-style(content) = text(fill: colourPalette.lightblueslate, weight: "bold")[#content]

= SAMENVATTING

#v(1em)

#chapter-style[Hoofdstuk 1] geeft ons een brede introductie over nucleïnezuur moleculen and hoe ze zijn geëvolueerd om deel te nemen in fysiologische processen die het menselijke leven onderhouden. We bespreken de modificaties die men kan toepassen om toegang te krijgen tot verbeterde of nieuwe eigenschappen en gebruiken deze synthetische nucleïnezuren voor farmaceutische applicaties. 
Een gedetailleerde uitleg wordt gegeven over hoe de structuur van dergelijke nucleïnezuur moleculen en de polymeren die ze opmaken kunnen _meten_.
Als laatste wordt er een overzicht gegeven over hoe we op een wiskundige manier moleculen kunnen interpreteren, door uit te wijden over het veld van _computationele chemie_. We beschrijven een molecule eerst naargelang de oriëntatie van diens kernen en elektronen, die ons de energie van het systeem oplevert. We brengen deze informatie over door middel van een _force field_ that ons toelaat het gedrag van het gewenste molecule te exploiteren voor molecular dynamics simulaties. Simuleren is het nabootsen hoe moleculen interageren met elkaar en hun omgeving zoals ze dat zouden doen in de werkelijkheid. 

//#chapter-style()[Chapter 1] gives us a broad introduction on nucleic acid molecules and how they evolved to partake in physiological processes to maintain human life. We discuss the modifications one can apply to access better or new properties and apply such synthetic nucleic acids for pharmaceutical applications. 
//A detailed explanation is given on how we can _measure_ the structure of nucleic acid molecules and their polymer structures.
//Lastly, an overview of how we mathematically interpret molecules is given by elaborating on the field of _Computational Chemistry_. First, we describe a molecule by the orientation of its nuclei and electrons, which returns us the energy of the system. We transfer this information through a _force field_ that allows us to exploit the desired molecule's behaviour during Molecular Dynamics simulations. To simulate is to mimic how molecules interact with each other and their environment as they would in real life.
//

In #chapter-style()[Hoofdstuk 2] concentreren we ons op de conformational sampling methodologie. Dit type experiment levert ons potentiaal energie oppervlaktes op waarmee we leren begrijpen welke _pucker_ modus een molecule van belang meer geschikt is om aan te nemen en dewelke het liever vermijdt. We hebben dit al eerder toegepast op gemodificeerde nucleïnezuren die interessant zijn voor ons lab, via een versnelde methodologie die het mogelijk maakt om de berekeningen op een lokaal werkstation te laten lopen. Het begrijpen en toepassen van wiskundige definities, gebruikt om deze landschappen te genereren, kan echter moeizaam verlopen en juist daarom introduceren we de _pucke.rs_ toolkit om het scripten van het experiment simpel te maken. Naast een maatstat studie om inzichtelijke data te bekomen over de verscheidene methoden in de computationele chemie, voorzien we een command line tool en Python module dat elke onderzoeker zou moeten helpen in het gebruiken van de methodologie voor hun eigen doeleinden zonder zich zorgen te moeten maken over de algebra achter de schermen. 

//In #chapter-style()[Chapter 2], we focus on the methodology of Conformational Sampling. This type of experiment returns us Potential Energy Surfaces with which we can understand the puckering modes a molecule of interest favours to adopt and which one it does not tend to visit. We have previously applied this on modified nucleic acids that are of interest to our lab, through an accelerated methodology that makes it manageable to run on a local workstation. However, understanding and applying the mathematical descriptions used to generate the landscapes can be cumbersome, which is why we introduce to _pucke.rs_ toolkit to simplify the scripting approach to this method. Alongside a benchmarking study to gather insightful data on the differences in methods of computational chemistry, we provide a command line tool and a Python library that should aid any researcher in applying the methodology for their own molecules without having to trouble themselves with the algebra that goes on behind it.  
//

De grootste vruchten van onze arbeid is gecondenseerd in #chapter-style()[Hoofdstuk 3]. De essentie is om nucleïnezuur helixen te genereren en modelleren aan de hand van een volledig computationeel protocol. We zijn geïnteresseerd in de Morpholino Nucleic Acid, die overigens veel gebruikt wordt in antisense oligonucleotide therapeutica. Jammer genoeg is de atoomstructuur ervan nog niet bepaald. Indien we het molecule verder willen kunnen exploiteren, moeten we de mogelijkheid krijgen om te verstaan hoe het zijn werking uitoefent op een fundamenteel niveau.
Als we de methodologie uit het vorige hoofdstuk gebruiken, kunnen we het gedrag van het molecule in kaart brengen. Informatie uit dit landschap kan dan gecureerd worden en ingebracht in de Ducque model builder om atoommodellen te produceren die gebruiksklaar zijn voor simulaties. 
Ducque werd ontworpen met het idee dat gebruikers hun eigen synthetische modificaties kunnen gebruiken om helicale modellen te bouwen, wat synergetisch vloeit met het eerdere conformational sampling experiment. 
De data van de Oppervlaktes kan ook gebruikt om een force field tot stand te brengen die moleculen correct beschrijft. Dit alles wordt samengesteld om nauwkeurige molecular dynamics simulaties uit te voeren voor eender welk type synthetische nucleïnezuur modificaties. 

//The largest fruits of our labour are condensed in #chapter-style()[Chapter 3]. The core idea is to be able to generate and model nucleic acid helices through a fully computational protocol. We are interested in the Morpholino Nucleic Acid, which has been heavily used in antisense oligonucleotide therapeutics. Unfortunately, its atomic structure is not yet determined. If we want to exploit the molecule further, we need to be able to rationalise how it exerts its power on a fundamental level.
//By using the methodology from the previous chapter, we can characterise the behaviour of a molecule. Information from this landscape can then be curated to insert into the Ducque model builder to build 3D atomic models, ready for simulations.
//Ducque has been designed to allow users to import custom chemistries to build their own helical models, which synergises specifically with the Conformational Sampling experiment.
//The data from the Surfaces can also be used to generate a force field that correctly describes the molecules. This can all be concatenated to perform accurate Molecular Dynamics simulations for any type of synthetic nucleic acid modification.
//
#chapter-style()[Hoofdstuk 4] is een verderzetting van het werk van dr. Charles-Alexandre Mattelaer. De gezamenlijke inspanning om de HNA aptameer te karakteriseren was een pittige taak die meerderige jaren vereiste om te volbrengen.
De experimentele labeur uitgevoerd door onze collega's in Cambridge, Londen en Sydney, maakte het mogelijk voor ons om de structuur van de nagenoeg onvatbare hen egg lysozyme aptameer te rationaliseren via _in silico_ methoden. Dankzij complementaire inspanningen zijn we er in geslaagd een structuur voor de HNA aptameer voor te leggen die een niet-kanoniek G-quadruplex motief bevat, die essentiëel is voor diens stabiliteit en dus ook het interactie potentiaal waarmee het bindt aan het enzyme.

//#chapter-style()[Chapter 4] is a continuation of the work of dr. Charles-Alexandre Mattelaer. The collaborative effort to characterise the HNA Aptamer was an arduous task that took several years to complete. Thanks to the experimental efforts conducted by our collaborators in Cambridge, London and Sydney, we were able to rationalise the structure of the elusive Hen Egg Lysozyme aptamer through _in silico_ means. Thanks to complementary efforts, we were able to devise that this HNA Aptamer structure contains a non-canonical G-quadruplex motif, which is essential to its stability and thus its interaction potential to the enzyme it binds to.
//

Ten slotte geeft #chapter-style()[Hoofdstuk 5] een wetenschappelijke discussie over de verscheidene aspecten van het weergegeven onderzoek, waarmee de thesis wordt geconcludeerd. We bespreken een project dat binnenkort het licht zal zien als een addendum voor de Ducque model builder.
//We hebben het over verscheidene programmeertalen die gebruikt worden binnen academisch onderzoek.
Een kleine discussie overloopt het faciliteren van computationeel onderzoek op XNA, onder meer het verbeteren van duidelijke protocollen voor parametrizatie en een betekenisvol onderscheid kunnen maken tussen nucleïnezuur structuren. 
De mogelijke uitkomsten van dit onderzoek worden op het einde behandeld.
//Finally,  #chapter-style()[Chapter 5] provides a scientific discussion on the various aspects of the presented research, effectively concluding the thesis. Firstly, we discuss a project that will soon see the light of day as an addendum to the Ducque model builder. 
//A small discussion elaborates on the facilitation of the computational study on XNA, on having clear protocols for parametrisation and to make meaningful distinctions for nucleic acid structures. Lastly, the possible outcomes of this research are discussed.
#pagebreak()
