#import "../../lib/multi-bib.typ": mcite
#import "bib_01_chapter.typ": biblio

== Introduction
Function and regulation of biopolymers is heavily influenced by conformational changes to amino acids and nucleosides that make up large proteins and nucleic acid structures respectively #mcite(("Lescrinier2003difference"), biblio).
//One of the most prominent traits in defining biomolecular function and regulation are conformational changes to the amino acids and nucleosides that make up large proteins and nucleic acid structures respectively.#mcite(("Lescrinier2003difference"), biblio)
It remains challenging to observe these changes directly at the atomic level due to their dynamic nature. Nonetheless, computer simulations have provided an increasingly realistic picture on the properties of studied molecules. MD simulations are often used to understand their behaviour by allowing molecules to visit one or more conformational states when freely interacting with their environment, or by imposing them with a restraintive bias to force less favourable states to occur as well during the simulation.#mcite(("Babin2006umbrella"), biblio) This behaviour is defined by a classical forcefield, whose parameters are typically obtained from research on particular moieties of the studied molecule, by either fitting to experimental data or using _ab initio_ calculations with QM #mcite(("Perez2007alphagamma", "Zgarbova2011rnaol3", "Zgarbova2015dnaol15"), biblio).
The latter field allows us to study virtual fragments through computational approaches and eventually predict the effect on the conformational behaviour of larger molecules that are composed of such fragments #mcite(("Huang2014improve", "Mattelaer2021efficient"), biblio).
Traditional force fields, used in the analysis of biopolymer structures and their interactions, rely on the quantitative descriptors of these monomer building blocks.#mcite(("Cornell19952ndgenff"), biblio)

In the field of synthetic NA research, this can guide the selection of new constructs prior to their synthesis in the lab. The development of XNAs advanced the field towards viable therapeutics #mcite(("Gait2022historyna"), biblio). Chemical modifications in the original DNA structure prolonged the biological half-life of oligonucleotides (ONs) to a level suited for clinical applications and interactions to the target were optimised to increase potency and selectivity #mcite(("Egli2023oligonucs"), biblio). Modifying the backbone and the nucleobase expanded the field of XNA research #mcite(("Pinheiro2012geneticpolymer", "Groaz2023hna", "Yang2023crispbases"), biblio). To date, progress was made by systematic approaches of chemical synthesis and evaluating the viability of a multitude of different XNA constructs.
Molecular modeling can exploit _in silico_ results and steer the selection of next generation XNA based therapeutics. A clearcut tool is needed to facilitate obtaining a free energy landscape for ring puckering of new nucleotides that can be used to derive forcefield parameters, which are required for MD simulations on larger constructs #mcite(("Rihon2024Ducque", "Schofield2023hnaaptamer"), biblio). 


//In this work, we present the _pucke.rs_ toolkit that generates the axes needed to produce the energy landscape of a molecule through Conformational Sampling (CS) methodology, by constructing the foundation of the energy landscape for specific molecular systems. We used the _pucke.rs_ commandline tool in cominbation with QM to fully characterise free energy landscapes by quantifying their potential wells and transitions between different states of the five-membered ring in the adenosine nucleoside, of the six-membered ring in an 1,5-anhydrohexitol NA (HNA) nucleoside and of the backbone in an alanine amino acid, using standard computational hardware. 
//The tool itself produces a set of constraints for all possible conformations of a molecular type, which are applied in geometry optimisation (GO) procedures, in order to produce a set of optimised conformers.
//The potential energy of the optimised conformers are calculated to obtain the energy levels of datapoints on the different landscapes (Single Point Evaluation, SPE).
//By using the _pucke.py_ module, the user can apply various formalisms (Cremer-Pople #mcite(("Cremer1975general", "Cremer1990analytical"), biblio), Altona-Sundaralingam #mcite(("Altona1972formalism"), biblio) or Strauss-Pickett #mcite(("Strauss1970conformational"), biblio)) to monomer constructs or to the respective monomers in a nucleic acid structure.
//This module can also generate the 3D structure of the corresponding five- or six-membered ring, based on queried puckering coordinates, proving useful to recreate molecules in reported literature.
//The DNA adenosine nucleoside was subjected to the CS methodology, exploiting a variety of different levels of theory in computational chemistry.
//The optimal procedure was selected to obtain high quality results in an acceptable timeframe by comparison of performances from different approaches on a local machine.
//We provide an in-depth look at puckering data from established literature and finish with a showcase on the various conformational landscapes of relevant biomolecules.

Here, we present the pucke.rs toolkit that generates the axes needed to produce the energy landscape of a molecule through conformational sampling. We demonstrate the toolkit with the adenosine nucleoside (dA), its HNA analogue and the alanine amino acid - using QM to fully characterise the free energy landscapes by quantifying their potential wells and transitions between different states. The axes provide a set of constraints for all possible conformations of a molecular type, which are applied in geometry optimisation (GO) procedures in QM, in order to produce a set of optimised conformers. The potential energy of the optimised conformers are then calculated to obtain the energy levels of datapoints on the different landscapes (Single Point Evaluation, SPE). Generating the axes for a specific landscape is accessible from the command line (_pucke.rs_) as well as a neat Python3 module (_pucke.py_). The latter additionally provides means to calculate for different formalisms (Cremer-Pople #mcite(("Cremer1975general", "Cremer1990analytical"), biblio), Altona-Sundaralingam #mcite(("Altona1972formalism"), biblio) or Strauss-Pickett #mcite(("Strauss1970conformational"), biblio) ), and it can use puckering coordinates to regenerate 3D structures of five- and six-membered rings (covering most frequent XNA chemical modifications). The module can also be used for assessing monomers in a polymer structure, thus enabling the determination of context-dependent conformations. The fast CS of monomers does not impair the accuracy of model assembly and it establishes modeling as a tool for discovery of novel XNAs.

