#import "../../lib/multi-bib.typ": mcite
#import "bib_01_chapter.typ": biblio

== Introduction


One of the most prominent traits in defining biomolecular function and regulation are conformational changes to the amino acids and nucleic acids that make up large proteins and nucleic acid structures respectively #mcite(("Lescrinier2003difference"), biblio). It remains challenging to observe these changes directly at the atomic level due to their dynamic nature. Nonetheless, computer simulations have provided an increasingly realistic picture on the properties of studied molecules. Molecular Dynamics (MD) simulations are often used to understand their behaviour by allowing molecules to visit one or more conformational states when freely interacting with their environment, or by imposing them with a restraintive bias to force less favourable states to occur as well during the simulation #mcite(("Babin2006umbrella"), biblio). This behaviour is defined by a classical forcefield, whose parameters are typically obtained from research on particular moieties of the studied molecule, by either fitting to experimental data or using _ab initio_ calculations with Quantum Mechanics (QM) #mcite(("Perez2007alphagamma", "Zgarbova2011rnaol3", "Zgarbova2015dnaol15"), biblio).
The latter field allows us to study virtual fragments through computational approaches and eventually predict the effect on the conformational behaviour of larger molecules that are composed of such fragments #mcite(("Huang2014improve", "Mattelaer2021efficient"), biblio).
Traditional force fields, used in the analysis of biopolymer structures and their interactions, rely on the quantitative descriptors of these monomer building blocks #mcite(("Cornell19952ndgenff"), biblio).

In the field of synthetic nucleic acid (NA) research, this can guide the selection of new constructs prior to their synthesis in the lab. The development of Xenobiotic Nucleic Acids (XNAs) advanced the field towards viable therapeutics #mcite(("Gait2022historyna"), biblio). Chemical modifications in the original DNA structure prolonged the biological half-life of oligonucleotides (ONs) to a level suited for clinical applications and interactions to the target were optimised to increase potency and selectivity #mcite(("Egli2023oligonucs"), biblio). Modifying the backbone and the nucleobase expanded the field of XNA research #mcite(("Pinheiro2012geneticpolymer", "Groaz2023hna", "Yang2023crispbases"), biblio). To date, progress was made by trial-and-error approaches of chemical synthesis and evaluating the viability of a multitude of different XNA constructs.
Molecular modeling can exploit _in silico_ results and steer the selection of next generation XNA based therapeutics. To induce this endeavor requires a clearcut tool needed to facilitate obtaining a free energy landscape for ring puckering of new nucleotides that can be used to derive forcefield parameters, which are required for MD simulations on larger constructs. 


In this work, we present the _pucke.rs_ toolkit to streamline the Conformational Sampling (CS) methodology, by constructing the foundation of the energy landscape for specific molecular systems. We used the _pucke.rs_ commandline tool and QM to fully characterise free energy landscapes by quantifying their potential wells and transitions between different states of the five-membered ring in the Adenosine nucleoside, of the six-membered ring in an 1,5-anhydrohexitol NA (HNA) nucleoside and of the backbone in an Alanine amino acid, using standard off-the-shelf computational hardware. 
The tool itself produces a set of constraints for all possible conformations of a molecular type, which are applied in geometry optimisation (GO) procedures, in order to produce a set of optimised conformers.
The potential energy of the optimised conformers are calculated to obtain the energy levels of datapoints on the different landscapes (Single Point Evaluation, SPE).
By using the _pucke.py_ module, the user can apply various formalisms (Cremer-Pople #mcite(("Cremer1975general", "Cremer1990analytical"), biblio), Altona-Sundaralingam #mcite(("Altona1972formalism"), biblio) or Strauss-Pickett #mcite(("Strauss1970conformational"), biblio)) to monomer constructs or to the respective monomers in a nucleic acid structure.
This module can also generate the 3D structure of the corresponding five- or six-membered ring, based on queried puckering coordinates, proving useful to recreate molecules in reported literature.
The DNA Adenosine nucleoside was subjected to the CS methodology, exploiting a variety of different levels of theory in computational chemistry.
The optimal procedure was selected to obtain high quality results in an acceptable timeframe by comparison of performances from different approaches on a local machine.
We provide an in-depth look at puckering data from established literature and finish with a showcase on the various conformational landscapes of relevant biomolecules.
